core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls')),
    path('', include('product.urls')),
    path('customers/', include('customer.urls')),
    path('sales/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views
app_name = 'customer'
urlpatterns = [
    path('', views.customer_list, name='customer_list'),
    path('detail/<int:pk>/', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('create/', views.CustomerCreateView.as_view(), name='customer_create'),
    path('edit/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer_edit'),
    path('delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='customer_delete'),
]

product/urls.py
from django.urls import path
from . import views
app_name = 'product'
urlpatterns = [
    path('',views.product_list,name='products'),
    path('tags/<slug:categories_slug>/',views.product_list,name='product_list_by_category'),
    path('add/', views.ProductCreateView.as_view(), name='product_add'),
    path('delete/<pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('edit/<pk>/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('detail/<pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('shell/<pk>',views.sale_create,name='product_shell'),
]

sale/urls.py
from django.urls import path
from . import  views

app_name = 'sales'

urlpatterns = [
    path('', views.sale_list, name='sale_list'),
    # path('<int:pk>/', SaleDetailView.as_view(), name='sale_detail'),
    path('create/', views.sale_create, name='sale_create'),
    path('edit/<int:pk>/', views.sale_edit, name='sale_edit'),
    path('delete/<int:pk>/', views.sale_delete, name='sale_delete'),
]

sale/models.py
from django.db import models
from django.contrib.auth.models import User
from customer.models import Customer
from product.models import Product
from django.conf import settings

class Sale(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sales')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='sales')
    products = models.ManyToManyField(Product, through='SaleProduct')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_profit = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Sale to {self.customer.name} on {self.created}"

class SaleProduct(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def convert_to_cup(self, amount, currency):
        if currency == 'USD':
            return amount * settings.USD_TO_CUP
        elif currency == 'MLC':
            return amount * settings.MLC_TO_CUP
        return amount

    @property
    def total_price(self):
        return self.convert_to_cup(self.product.price, self.product.currency) * self.quantity

    @property
    def total_profit(self):
        return self.convert_to_cup(self.product.high_price - self.product.price, self.product.currency) * self.quantity

sale/forms.py
from django import forms
from .models import Sale, SaleProduct
from product.models import Product

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['customer']

#-----------------------------------------------------------------

class SaleProductForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    class Meta:
        model = SaleProduct
        fields = ['product', 'quantity']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
        }

    def clean_product(self):
        product = self.cleaned_data.get('product')
        if product is None:
            raise forms.ValidationError("No product selected")
        return product

    def clean_quantity(self):
        cd = self.cleaned_data
        quantity = cd.get('quantity')
        product = cd.get('product')
        if product:
            if quantity and (quantity > product.remaining_stock()):
                raise forms.ValidationError('Not enough quantity available for this product.')
        if quantity <= 0:
            raise forms.ValidationError('Must be greater than 0')
        return quantity


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.all()
        self.fields['product'].label_from_instance = lambda obj: f"{obj.name} [{obj.remaining_stock()}]"

sale/views.py
from django  import forms
from django.conf import settings
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from .models import Sale

@login_required
def sale_list(request):
    query = request.GET.get('q', '')
    sale_list = Sale.objects.filter(user=request.user)

    if query:
        sale_list = sale_list.filter(
            Q(customer__name__icontains=query) |
            Q(products__name__icontains=query)
        ).distinct()

    items_per_page = request.GET.get('items_per_page', 5)

    order_by = request.GET.get('order_by', 'created')
    ordering = request.GET.get('ordering', 'desc')
    valid_order_fields = ['customer__name', 'created', 'updated', 'total_price', 'total_profit']

    if order_by not in valid_order_fields:
        order_by = 'created'

    if ordering == 'desc':
        order_by = f'-{order_by}'

    sale_list = sale_list.order_by(order_by)

    paginator = Paginator(sale_list, items_per_page)

    page_number = request.GET.get('page', 1)
    try:
        sales = paginator.page(page_number)
    except PageNotAnInteger:
        sales = paginator.page(1)
    except EmptyPage:
        sales = paginator.page(paginator.num_pages)


    class Currency:
        def __init__(self, typos, values):
            self.values = values
            self.typos = typos

    dollar_change = [Currency("USD_TO_CUP",settings.USD_TO_CUP),
                     Currency("EUR_TO_CUP",settings.EUR_TO_CUP),
                     Currency("MLC_TO_CUP",settings.MLC_TO_CUP),]

    return render(request, 'sales/sale_list.html', {
        'sales': sales,
        'items_per_page': items_per_page,
        'order_by': order_by.lstrip('-'),
        'ordering': 'desc' if order_by.startswith('-') else 'asc',
        'query': query,
        'section': 'sales',
        'dollar_change': dollar_change,
    })


# views.py en la aplicación de Sales
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Sale, SaleProduct
from .forms import SaleForm, SaleProductForm
from customer.models import Customer
from product.models import Product

@transaction.atomic
@login_required
def sale_create(request):
    SaleProductFormSet = inlineformset_factory(Sale, SaleProduct, form=SaleProductForm, extra=1, can_delete=True)
    if request.method == 'POST':
        sale_form = SaleForm(request.POST)
        formset = SaleProductFormSet(request.POST)

        if sale_form.is_valid() and formset.is_valid():
            products_selected  = []
            for index,form in enumerate(formset):
                if not form.cleaned_data or not form.cleaned_data['product']:
                    messages.error(request,f"The form {index+1} is empty.")
                    return render(request, 'sales/sale_form.html', {
                        'sale_form': sale_form,
                        'formset': formset,
                        'customers': Customer.objects.all(),
                        'products': Product.objects.all(),
                        'is_editing':False
                    })
                if form.cleaned_data['product'] in products_selected:
                    messages.error(request,f"The product {form.cleaned_data['product']} already selected.")
                    return render(request, 'sales/sale_form.html', {
                        'sale_form': sale_form,
                        'formset': formset,
                        'customers': Customer.objects.all(),
                        'products': Product.objects.all(),
                        'is_editing':False
                    })
                products_selected.append(form.cleaned_data['product'])

            sale = sale_form.save(commit=False)
            sale.total_profit = 0
            sale.total_price = 0
            sale.user = request.user
            sale.save()  # Guardar la venta primero

            total_price = 0
            total_profit = 0
            products = []
            for form in formset:
                sale_product = form.save(commit=False)
                sale_product.sale = sale
                sale_product.save()
                total_price += sale_product.total_price
                total_profit += sale_product.total_profit
                    # Update sold_quantity
                product = sale_product.product
                product.sold_quantity += sale_product.quantity
                product.save()
            # Update total price and profit for the sale
            sale.total_price = total_price
            sale.total_profit = total_profit
            sale.save()

            messages.success(request, "Sale was created successfully!")
            return redirect('sales:sale_list')
        else:
            # If the form or formset is not valid, render the form again with errors
            return render(request, 'sales/sale_form.html',
                          { 'sale_form': sale_form, 'formset': formset,
                            'is_editing':False
                            })
    else:
        sale_form = SaleForm()
        formset = SaleProductFormSet()
        return render(request, 'sales/sale_form.html', {
            'sale_form': sale_form,
            'formset': formset,
            'is_editing': False,
        })

@login_required
def sale_edit(request, pk):
    sale = get_object_or_404(Sale, pk=pk, user=request.user)
    SaleProductFormSet = inlineformset_factory(Sale, SaleProduct, form=SaleProductForm, extra=0, can_delete=True)

    if request.method == 'POST':
        sale_form = SaleForm(request.POST)
        formset = SaleProductFormSet(request.POST)

        if sale_form.is_valid() and formset.is_valid():
            sale = sale_form.save(commit=False)
            sale.total_profit = 0
            sale.total_price = 0
            sale.save()

            total_price = 0
            total_profit = 0
            formset.save(commit=False)

            for form in formset:
                sale_product = form.save(commit=False)
                sale_product.sale = sale
                sale_product.save()
                total_price += sale_product.total_price
                total_profit += sale_product.total_profit
                product = sale_product.product
                product.sold_quantity += sale_product.quantity
                product.save()

            sale.total_price = total_price
            sale.total_profit = total_profit
            sale.save()

            messages.success(request, "Sale was updated successfully!")
            return redirect('sales:sale_list')
        else:
            messages.error(request, "error while updating sale.")
    else:
        sale_form = SaleForm(instance=sale)
        formset = SaleProductFormSet(instance=sale)

    return render(request, 'sales/sale_form.html', {
        'sale_form': sale_form,
        'formset': formset,
        'sale': sale,
        'is_editing': True
    })



@login_required
def sale_delete(request, pk):
    sale = get_object_or_404(Sale, pk=pk, user=request.user)
    if request.method == 'POST':
        products  = sale.products.all()
        for p in products:
            p.sold_quantity -= get_object_or_404(SaleProduct,product=p,sale=sale).quantity
            p.save()

        sale.delete()

        messages.success(request, "The Sale has been deleted successfully!")
        return redirect('sales:sale_list')
    return render(request, 'sales/sale_confirm_delete.html', {'sale': sale})

def functionforgreeningithub(request):
    pass
def sumarpuntosengithub(request):
    pass
def sumpuntosgit(request):
    pass

sale/templates/sales/sale_confirm_delete.html
{% extends "base.html" %}

{% block title %}Eliminar Venta{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title mb-4">Delete this sale</h5>
                    <p>Are you sure you want to delete</p>
                    <p>{{ sale }}</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'sales:sale_list' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

sale/templates/sales/sale_form.html
{% extends "base.html" %}

{% block title %}Create Sale{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm mb-3">
                <div class="card-body">
                    <h5 class="card-title text-center mb-4">Create Sale</h5>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="id_customer" class="form-label">Customer</label>
                            <div class="d-flex">
                                <select class="form-select" id="id_customer" name="customer">
                                    <option value="">Select a customer</option>
                                    {% for customer in sale_form.customer.field.queryset %}
                                        <option value="{{ customer.id }}" {% if sale_form.customer.value|stringformat:'s' == customer.id|stringformat:'s' %}selected{% endif %}>
                                            {{ customer.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                                <a href="{% url 'customer:customer_create' %}?next=sale_create" class="btn btn-outline-secondary ms-2">
                                    <i class="bi bi-plus" style="font-size: 18px;"></i>
                                </a>
                            </div>
                            {% for error in sale_form.customer.errors %}
                                <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="formset">
                            {{ formset.management_form }}
                            {% for form in formset %}
                                <div class="card mb-3">
                                    <div class="card-body">
                                        {{ form.non_field_errors }}
                                        <div class="d-md-inline-flex">
                                            <div class="w-75 pe-2">
                                                {{ form.product.label_tag }}
                                                {{ form.product }}
                                                {% for error in form.product.errors %}
                                                    <div class="text-danger">{{ error }}</div>
                                                {% endfor %}
                                            </div>
                                            <div class="w-50">
                                                {{ form.quantity.label_tag }}
                                                {{ form.quantity }}
                                                {% for error in form.quantity.errors %}
                                                    <div class="text-danger">{{ error }}</div>
                                                {% endfor %}
                                            </div>
                                            <div>
                                                <label>Actions:</label>
                                                <div class="d-inline-flex justify-content-center align-items-center">

                                                <a href="{% url 'product:product_add' %}?next=sale_create" class="btn btn-outline-secondary ms-2">
                                                    <i class="bi bi-plus" style="font-size: 18px;"></i>
                                                </a>
                                                    <button type="button" class="btn btn-outline-danger ms-2 remove-form" onclick="removeForm(this)">
                                                     <i class="bi bi-trash3"></i>
                                                    </button>
                                                </div>
                                            </div>


                                        </div>

                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if is_editing %}
                            Update Sale
                            {% else %}
                            Create Sale
                            {% endif %}

                        </button>
                        <button type="button" class="btn btn-secondary" id="add-more">Add More Products</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('add-more').onclick = function() {
        let formset = document.querySelector('.formset');
        let formCount = parseInt(document.querySelector('#id_saleproduct_set-TOTAL_FORMS').value);
        let newForm = formset.querySelector('.card').cloneNode(true);
        newForm.querySelectorAll('input, select, textarea').forEach(function(input) {
            let name = input.getAttribute('name').replace(/-\d+-/, `-${formCount}-`);
            input.setAttribute('name', name);
            input.setAttribute('id', `id_${name}`);
            if (input.tagName === 'INPUT') {
                input.value = '';
            }
        });
        formset.querySelector('#id_saleproduct_set-TOTAL_FORMS').value = formCount + 1;
        formset.appendChild(newForm);
    }
});

function removeForm(button) {
    let formset = document.querySelector('.formset');
    if (formset.querySelectorAll('.card').length > 1) {
        button.closest('.card').remove();
        let formCount = parseInt(document.querySelector('#id_saleproduct_set-TOTAL_FORMS').value) - 1;
        document.querySelector('#id_saleproduct_set-TOTAL_FORMS').value = formCount;
    }
}
</script>
{% endblock content %}

sale/templates/sales/sale_list.html
{% extends "base.html" %}

{% block title %}Sales{% endblock title %}

{% block content %}
<div class="container mt-4">
{% if not sales %}
    <div class="alert alert-warning text-center mt-4">
        <p>No sales found. Please add new Sale.</p>
        <a href="{% url 'sales:sale_create' %}"
           class="btn btn-primary">Add New Sale</a>
        <div class="mt-3"> <i class="bi bi-arrow-down-circle" style="font-size: 2rem;"></i>
        </div>
    </div>
    {% else %}
    <h2>Sales List</h2>

    <div class="d-flex justify-content-between align-items-center mt-3">
        <form class="form-inline" method="get" action="">
            <div class="form-group mb-2">
                <label for="order_by" class="mr-2">Order by:</label>
                <select class="form-control" name="order_by" id="order_by">
                    <option value="customer__name" {% if request.GET.order_by == "customer__name" %}selected{% endif %}>Customer</option>
                    <option value="created" {% if request.GET.order_by == "created" %}selected{% endif %}>Created</option>
                    <option value="updated" {% if request.GET.order_by == "updated" %}selected{% endif %}>Updated</option>
                    <option value="total_price" {% if request.GET.order_by == "total_price" %}selected{% endif %}>Total Price</option>
                    <option value="total_profit" {% if request.GET.order_by == "total_profit" %}selected{% endif %}>Total Profit</option>
                </select>
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="asc" name="ordering" value="asc" {% if request.GET.ordering == "asc" %}checked{% endif %} onclick="ensureSingleCheck(this)">
                    <label class="form-check-label" for="asc">Ascending</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="desc" name="ordering" value="desc" {% if request.GET.ordering == "desc" %}checked{% endif %} onclick="ensureSingleCheck(this)">
                    <label class="form-check-label" for="desc">Descending</label>
                </div>
            </div>
            <div class="d-inline-flex w-100 justify-content-between">
                <button type="submit" class="btn btn-primary mb-2">Sort</button>
                <a href=""><button type="reset" class="btn btn-secondary mb-2">Reset</button></a>
            </div>
        </form>
        <div>
           {% for dc in dollar_change %}
            <p>{{ dc.typos }}: ${{ dc.values }} CUP</p>
            {% endfor %}
        </div>



        <!-- Search Form -->
        <form class="form-inline" method="get" action="">
            <div class="form-group mb-2">
                <input type="text" class="form-control" name="q" placeholder="Search" value="{{ request.GET.q }}">
            </div>
            <div class="d-inline-flex w-100 justify-content-between">
                <button type="submit" class="btn btn-primary mb-2">Search</button>
                <a href=""><button type="reset" class="btn btn-secondary mb-2">Reset</button></a>
            </div>
        </form>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Products</th>
                    <th>Customer</th>
                    <th>Total Price</th>
                    <th>Total Profit</th>
                    <th>Created</th>
                    <th>Updated</th>

                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% if sales %}
                    {% for sale in sales %}
                        <tr>
                            <td>
                                {% for product in sale.products.all %}
                                    {{ product.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ sale.customer.name }}</td>
                             <td>{{ sale.total_price }} CUP</td>
                            <td>{{ sale.total_profit }} CUP</td>
                            <td>{{ sale.created }}</td>
                            <td>{{ sale.updated }}</td>

                            <td class="actions-column">
{#                                <a href="{% url "sales:sale_detail" sale.id %}" class="btn btn-info btn-sm">Details</a>#}
                                <a href="{% url "sales:sale_edit" sale.id %}" class="btn btn-warning btn-sm">Edit</a>
                                <a href="{% url "sales:sale_delete" sale.id %}" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="7" class="text-center">No sales found. <a href="{% url 'sales:sale_create' %}">Add a new sale</a> <i class="bi bi-arrow-right"></i></td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if sales.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ sales.previous_page_number }}&items_per_page={{ items_per_page }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for num in sales.paginator.page_range %}
                {% if sales.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% elif num > sales.number|add:'-5' and num < sales.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}&items_per_page={{ items_per_page }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if sales.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ sales.next_page_number }}&items_per_page={{ items_per_page }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
<!-- Floating Action Button -->
<a href="{% url "sales:sale_create" %}" class="btn btn-primary btn-lg rounded-circle shadow"
style="position: fixed; bottom: 20px; right: 20px; width: 60px; height: 60px; display: flex; justify-content: center; align-items: center;">
    <i class="bi bi-plus" style="font-size: 24px;"></i>
</a>
    {% endif %}
<script>
function ensureSingleCheck(element) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"][name="ordering"]');
    checkboxes.forEach(function (checkbox) {
        if (checkbox !== element) checkbox.checked = false;
    });
}
</script>
{% endblock content %}