core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls')),
    path('', include('product.urls')),
    path('customers/', include('customer.urls')),
    path('sales/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views
app_name = 'product'
urlpatterns = [
    path('',views.product_list,name='products'),
    path('tags/<slug:categories_slug>/',views.product_list,name='product_list_by_category'),
    path('add/', views.ProductCreateView.as_view(), name='product_add'),
    path('delete/<pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('edit/<pk>/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('detail/<pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('shell/<pk>',views.sale_create,name='product_shell'),
]

resell/urls.py
from django.urls import path
from . import views
app_name = 'resell'
urlpatterns = [
    path('',views.product_list,name='products'),
    path('tags/<slug:categories_slug>/',views.product_list,name='product_list_by_category'),
    path('add/', views.ProductCreateView.as_view(), name='product_add'),
    path('delete/<pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('edit/<pk>/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('detail/<pk>', views.ProductDetailView.as_view(), name='product_detail'),
]

product/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.

class Product(models.Model):
    class Status(models.TextChoices):
        CUP = 'CUP','CUP'
        USD = 'USD','USD'
        MLC = 'MLC','MLC'
    name = models.CharField(max_length=100)
    retailer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    high_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    sold_quantity = models.PositiveIntegerField(default=0)
    currency = models.CharField(max_length=10, choices=Status.choices, default=Status.CUP)
    unit = models.CharField(max_length=50,default='unit')
    categories = TaggableManager(verbose_name='Categories', blank=True)
    #time
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def expected_profit(self):
        return (self.high_price - self.price) * self.quantity

    def investment(self):
        return self.price * self.quantity

    def potential_profit(self):
        return (self.high_price - self.price) * (self.quantity - self.sold_quantity)

    def profit_so_far(self):
        return (self.high_price - self.price) * self.sold_quantity

    def remaining_stock(self):
        return self.quantity - self.sold_quantity

    def progress_percent(self):
        return (self.sold_quantity / self.quantity) * 100 if self.quantity > 0 else 0

    class Meta:
        ordering = ['-created']
        # provide index, improve performance for queries filtering
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

product/forms.py
from django import forms

from sale.models import SaleProduct
from .models import Product
from taggit.forms import TagWidget
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'high_price', 'quantity', 'currency', 'unit', 'categories']

        widgets = {
            'categories': TagWidget(),
        }

class ProductSellForm(forms.ModelForm):
    class Meta:
        model = SaleProduct
        fields = ['quantity']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
        }
    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity <= 0:
            raise forms.ValidationError("Quantity must be greater than 0.")
        return quantity

product/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.shortcuts import render,get_object_or_404

from sale.models import SaleProduct
from sale.templates.salvadesaleform.forms import SaleForm
from .models import Product
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.detail import DetailView
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import F, DecimalField, Value as V
from django.db.models import F, ExpressionWrapper, DecimalField, Value as V
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin
from .forms import ProductForm, ProductSellForm


# Create your views here.
@login_required
def product_list(request, categories_slug=None):
    query = request.GET.get('q', '')
    product_list = Product.objects.filter(retailer=request.user)
    category = None

    if categories_slug:
        category = get_object_or_404(Tag, slug=categories_slug)
        product_list = product_list.filter(categories__in=[category])


    if query:
        product_list = product_list.filter(
            Q(name__icontains=query) |
            Q(categories__name__icontains=query)
        ).distinct()


    items_per_page = request.GET.get('items_per_page', 5)


    product_list = product_list.annotate(
        cost=ExpressionWrapper(
            F('price') * F('quantity'),
            output_field=DecimalField()
        ),
        expected_profit=ExpressionWrapper(
            (F('high_price') - F('price')) * F('quantity'),
            output_field=DecimalField()
        ),
        price_cup=ExpressionWrapper(
            F('price') *
            (F('currency') == 'USD' and settings.USD_TO_CUP or
             F('currency') == 'MLC' and settings.MLC_TO_CUP or 1),
            output_field=DecimalField()
        )
    )


    order_by = request.GET.get('order_by', 'created')
    ordering = request.GET.get('ordering', 'desc')
    valid_order_fields = ['name', 'price', 'high_price', 'currency', 'quantity', 'expected_profit', 'cost', 'created', 'updated']

    if order_by not in valid_order_fields:
        order_by = 'name'

    if ordering == 'desc':
        order_by = f'-{order_by}'

    product_list = product_list.order_by(order_by)

    paginator = Paginator(product_list, items_per_page)

    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'products/product_list.html', {
        'products': products,
        'category': category,
        'items_per_page': items_per_page,
        'order_by': order_by.lstrip('-'),
        'ordering': 'desc' if order_by.startswith('-') else 'asc',
        'query': query,
        'section': 'products'
    })


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'



class ProductCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_add.html'
    success_url = reverse_lazy('product:products')
    success_message = "Product was created successfully!"

    def form_valid(self, form):
        form.instance.retailer = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was an error creating the product. Please try again.")
        return super().form_invalid(form)


class ProductUpdateView(LoginRequiredMixin,SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_edit.html'
    success_url = reverse_lazy('product:products')
    success_message = "Product was updated successfully!"

    def form_valid(self, form):
        form.instance.retailer = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was an error updating the product. Please try again.")
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = self.object.categories.all()
        context['formatted_categories'] = ', '.join([tag.name for tag in categories])
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/product_delete.html'
    success_url = reverse_lazy('product:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_name'] = self.get_object().name
        return context

    def form_valid(self, form):
        messages.success(self.request, "Product deleted successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error deleting product')
        return super().form_invalid(form)


@transaction.atomic
@login_required
def sale_create(request,pk):
    product = get_object_or_404(Product, pk=pk, retailer=request.user)
    if request.method == 'POST':
        sale_form = SaleForm(request.POST)
        product_form = ProductSellForm(request.POST)
        quantity = 0
        if request.POST.get('quantity'):
            quantity = int(request.POST.get('quantity'))
        else:
            messages.error(request, "Quantity cannot be empty")
            return render(request, 'products/product_sell.html', {
                'product_form': product_form,
                'sale_form': sale_form,
                'remaining': product.remaining_stock(),
            })



        if quantity > product.remaining_stock():
            messages.error(request, "You don't have enough stock to sell this product.")
            return render(request,'products/product_sell.html',{
                'product_form': product_form,
                'sale_form': sale_form,
                'remaining': product.remaining_stock(),
            })


        if sale_form.is_valid() and product_form.is_valid():
            sale = sale_form.save(commit=False)
            sale.total_price = 0
            sale.total_profit = 0
            sale.user = request.user
            sale.save()

            sale_product = SaleProduct(product=product, quantity=quantity,sale=sale)
            sale_product.save()
            sale.total_price = sale_product.total_price
            sale.total_profit = sale_product.total_profit
            sale.save()
            messages.success(request, "Sale was created successfully!")
            return redirect('sales:sale_list')
        else:

            return render(request,'products/product_sell.html',{
                'product_form': product_form,
                'sale_form': sale_form,
                'remaining': product.remaining_stock(),
            })
    else:
        sale_form = SaleForm()
        product_form = ProductSellForm()
        return render(request,'products/product_sell.html',{
            'product_form': product_form,
            'sale_form': sale_form,
            'remaining': product.remaining_stock(),

        })

resell/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404
from .models import Product
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.detail import DetailView
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import F, DecimalField, Value as V
from django.db.models import F, ExpressionWrapper, DecimalField, Value as V
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin
from .forms import ProductForm

from django.views.generic.edit import FormView
# Create your views here.
@login_required
def product_list(request, categories_slug=None):
    query = request.GET.get('q', '')
    product_list = Product.objects.filter(retailer=request.user)
    category = None

    if categories_slug:
        category = get_object_or_404(Tag, slug=categories_slug)
        product_list = product_list.filter(categories__in=[category])


    if query:
        product_list = product_list.filter(
            Q(name__icontains=query) |
            Q(categories__name__icontains=query)
        ).distinct()


    items_per_page = request.GET.get('items_per_page', 5)


    product_list = product_list.annotate(
        cost=ExpressionWrapper(
            F('price') * F('quantity'),
            output_field=DecimalField()
        ),
        expected_profit=ExpressionWrapper(
            (F('high_price') - F('price')) * F('quantity'),
            output_field=DecimalField()
        ),
        price_cup=ExpressionWrapper(
            F('price') *
            (F('currency') == 'USD' and settings.USD_TO_CUP or
             F('currency') == 'MLC' and settings.MLC_TO_CUP or 1),
            output_field=DecimalField()
        )
    )


    order_by = request.GET.get('order_by', 'created')
    ordering = request.GET.get('ordering', 'desc')
    valid_order_fields = ['name', 'price', 'high_price', 'currency', 'quantity', 'expected_profit', 'cost', 'created', 'updated']

    if order_by not in valid_order_fields:
        order_by = 'name'

    if ordering == 'desc':
        order_by = f'-{order_by}'

    product_list = product_list.order_by(order_by)

    paginator = Paginator(product_list, items_per_page)

    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'products/product_list.html', {
        'products': products,
        'category': category,
        'items_per_page': items_per_page,
        'order_by': order_by.lstrip('-'),
        'ordering': 'desc' if order_by.startswith('-') else 'asc',
        'query': query,
        'section': 'products'
    })


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'



class ProductCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_add.html'
    success_url = reverse_lazy('resell:products')
    success_message = "Product was created successfully!"

    def form_valid(self, form):
        form.instance.retailer = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was an error creating the product. Please try again.")
        return super().form_invalid(form)


class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_edit.html'
    success_url = reverse_lazy('resell:products')
    success_message = "Product was updated successfully!"

    def form_valid(self, form):
        form.instance.retailer = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was an error updating the product. Please try again.")
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = self.object.categories.all()
        context['formatted_categories'] = ', '.join([tag.name for tag in categories])
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/product_delete.html'
    success_url = reverse_lazy('resell:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_name'] = self.get_object().name
        return context

    def form_valid(self, form):
        messages.success(self.request, "Product deleted successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error deleting product')
        return super().form_invalid(form)

resell/templates/products/product_add.html
{% extends "base.html" %}

{% block title %}Create Product{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-start vh-100">
    <div class="card shadow-sm mt-5" style="width: 24rem;">
        <div class="card-body">
        <div class="flex-row justify-content-between ">
            <a href="{% url "resell:products" %}">
            <button type="button" class="btn btn-light">
                <i class="bi bi-arrow-left-short fs-2">
                </i>
            </button>
            </a>

            <h5 class="card-title text-center mb-4">Create Product</h5>
        </div>

            <form method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}

                <div class="mb-3">
                    <label for="id_name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="id_name" name="name">
                    {% if form.name.errors %}
                        <div class="text-danger">
                            {{ form.name.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_price" class="form-label">Price</label>
                    <input type="number" step="0.01" class="form-control" id="id_price" name="price">
                    {% if form.price.errors %}
                        <div class="text-danger">
                            {{ form.price.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_high_price" class="form-label">High Price</label>
                    <input type="number" step="0.01" class="form-control" id="id_high_price" name="high_price">
                    {% if form.high_price.errors %}
                        <div class="text-danger">
                            {{ form.high_price.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_quantity" class="form-label">Quantity</label>
                    <input type="number" class="form-control" id="id_quantity" name="quantity">
                    {% if form.quantity.errors %}
                        <div class="text-danger">
                            {{ form.quantity.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_currency" class="form-label">Currency</label>
                    <select class="form-select" id="id_currency" name="currency">
                        {% for choice in form.currency.field.choices %}
                            <option value="{{ choice.0 }}" {% if form.currency.value == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    {% if form.currency.errors %}
                        <div class="text-danger">
                            {{ form.currency.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_unit" class="form-label">Unit</label>
                    <input type="text" class="form-control" id="id_unit" name="unit" value="{{ form.unit.value|default:'unit' }}">
                    {% if form.unit.errors %}
                        <div class="text-danger">
                            {{ form.unit.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_categories" class="form-label">Categories</label>
                    <input type="text" class="form-control" id="id_categories" name="categories"  placeholder="Separated by comma">
                    {% if form.categories.errors %}
                        <div class="text-danger">
                            {{ form.categories.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Create Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

resell/templates/products/product_delete.html
{% extends "base.html" %}

{% block title %}Delete Product{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card shadow-sm mt-5" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title text-center mb-4">Delete Product</h5>
            <p class="text-center">Are you sure you want to delete this product?</p>
            <div class="text-primary text-center fs-4 ">
                <p>{{product_name}}</p>
            </div>
            
            <form method="post">
                {% csrf_token %}
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a href="{% url 'resell:products' %}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

resell/templates/products/product_detail.html
{% extends "base.html" %}

{% block title %}Product Details{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ product.get_currency_display }}</h6>
            <p class="card-text">Price: {{ product.price }} {{ product.currency }}</p>
            <p class="card-text">High Price: {{ product.high_price }} {{ product.currency }}</p>
            <p class="card-text">Quantity: {{ product.quantity }} {{ product.unit }}{{ product.quantity|pluralize }}</p>
            <p class="card-text">Investment(inversión): {{ product.investment|floatformat:2 }} {{ product.currency }}</p>
            <p class="card-text">Profit So Far(lo que se ha ganado): {{ product.profit_so_far|floatformat:2 }} {{ product.currency }}</p>
            <p class="card-text">Potential Profit(lo que se espera ganar): {{ product.potential_profit|floatformat:2 }} {{ product.currency }}</p>
            <p class="card-text">Sold Quantity(lo que se ha vendido): {{ product.sold_quantity }} {{ product.unit }}{{ product.sold_quantity|pluralize }}</p>
            <p class="card-text">Remaining Stock(lo que queda): {{ product.remaining_stock }} {{ product.unit }}{{ product.remaining_stock|pluralize }}</p>
            <div class="progress mb-3">
                <div class="progress-bar" role="progressbar" style="width: {{ product.progress_percent }}%;" aria-valuenow="{{ product.progress_percent }}" aria-valuemin="0" aria-valuemax="100">
                    {{ product.progress_percent|floatformat:2 }}%
                </div>
            </div>
            <p class="card-text">Categories:
                {% for category in product.categories.all %}
                    <span class="badge bg-primary">{{ category.name }}</span>
                {% endfor %}
            </p>
            

            <a href="#" class="btn btn-primary">Resell</a>
            <a href="{% url 'resell:products' %}" class="btn btn-secondary">Back</a>

        </div>
    </div>
</div>
{% endblock content %}

resell/templates/products/product_edit.html
{% extends "base.html" %}

{% block title %}Create Product{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-start vh-100">
    <div class="card shadow-sm mt-5" style="width: 24rem;">
        <div class="card-body">
             <div class="flex-row justify-content-between ">
            <a href="{% url "resell:products" %}">
            <button type="button" class="btn btn-light">
                <i class="bi bi-arrow-left-short fs-2">
                </i>
            </button>
            </a>

            <h5 class="card-title text-center mb-4">Edit Product</h5>
        </div>
            <form method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="id_name" name="name" value="{{ form.name.value|default:'' }}">
                    {% if form.name.errors %}
                        <div class="text-danger">
                            {{ form.name.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_price" class="form-label">Price</label>
                    <input type="number" step="0.01" class="form-control" id="id_price" name="price" value="{{ form.price.value|default:'' }}">
                    {% if form.price.errors %}
                        <div class="text-danger">
                            {{ form.price.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_high_price" class="form-label">High Price</label>
                    <input type="number" step="0.01" class="form-control" id="id_high_price" name="high_price" value="{{ form.high_price.value|default:'' }}">
                    {% if form.high_price.errors %}
                        <div class="text-danger">
                            {{ form.high_price.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_quantity" class="form-label">Quantity</label>
                    <input type="number" class="form-control" id="id_quantity" name="quantity" value="{{ form.quantity.value|default:'' }}">
                    {% if form.quantity.errors %}
                        <div class="text-danger">
                            {{ form.quantity.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_currency" class="form-label">Currency</label>
                    <select class="form-select" id="id_currency" name="currency">
                        {% for choice in form.currency.field.choices %}
                            <option value="{{ choice.0 }}" {% if form.currency.value == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    {% if form.currency.errors %}
                        <div class="text-danger">
                            {{ form.currency.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_unit" class="form-label">Unit</label>
                    <input type="text" class="form-control" id="id_unit" name="unit" value="{{ form.unit.value|default:'unit' }}">
                    {% if form.unit.errors %}
                        <div class="text-danger">
                            {{ form.unit.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_categories" class="form-label">Categories</label>
                    <input type="text" class="form-control" id="id_categories" name="categories"
                           value="{{ formatted_categories|default_if_none:''}}"
                           placeholder="Separated by comma">
                    {% if form.categories.errors %}
                        <div class="text-danger">
                            {{ form.categories.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}